[workspace]
members = [
    "radish/radish-core",
    "radish/radish-fetch",
    "radish/radish-render",
    "radish/radish-cli",
    "radish/radish-web",
    "radish/radish-worker",
    "plugins/layer-basemap/crate",
    "plugins/layer-radar-l2/crate",
    "plugins/layer-noaa-alerts/crate",
    "plugins/layer-radar-sites/crate",
]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
