/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const run: () => void;
export const send_command: (a: number, b: number) => void;
export const add_scan: (a: number, b: number, c: number, d: number, e: number, f: any, g: any) => void;
export const commit_volume: (a: number, b: number, c: number, d: number) => void;
export const update_layer_texture: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const set_state_callback: (a: any) => void;
export const set_alert_click_callback: (a: any) => void;
export const set_site_click_callback: (a: any) => void;
export const wasm_bindgen__closure__destroy__h24c0febaa5b40e0a: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h3db7abc61f8e5d62: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h46c90cb28d789240: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hc51d8872d0699caa: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__he4022f8a72ca9bbd: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01d21ced2ba20a8c: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01d21ced2ba20a8c_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01d21ced2ba20a8c_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01d21ced2ba20a8c_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01d21ced2ba20a8c_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01d21ced2ba20a8c_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01d21ced2ba20a8c_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01d21ced2ba20a8c_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5fcd186093bb5428: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hf9f65cc588f8f19b: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h5a06bf4804e266ad: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
