name = "nexrad"
main = "src/main.ts"
# compatibility_flags = ["python_workers"]
compatibility_date = "2024-03-29"
node_compat = true

[[kv_namespaces]]
binding = "cache"
id = "35682aa1a2d34a94b58c71f3f7746ff4"

[dev]
port = 8787
