[package]
name = "nexrad-worker"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
nexrad-core = { path = "../nexrad-core", features = ["parse"] }
nexrad-fetch = { path = "../nexrad-fetch" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
postcard = { version = "1", features = ["alloc"] }
console_error_panic_hook = "0.1"
